CREATE TABLE [CSF_PERMISOS].[adm].[SOLAXI](
	[SOLAXICOD] [int] IDENTITY(1,1) NOT NULL,
    [SOLAXICAB] [int] NOT NULL,
	[SOLAXIEST] [char](1) NULL,
    [SOLAXISOL] [char](1) NULL,
	[SOLAXIDOC] [varchar](100) NULL,
    [SOLAXIFED] [date] NULL,
	[SOLAXIFEH] [date] NULL,
    [SOLAXIAPD] [date] NULL,
	[SOLAXIAPH] [date] NULL,
	[SOLAXICAN] [int] NULL,
    [SOLAXITIP] [char](8) NULL,
	[SOLAXIDIA] [int] NULL,
    [SOLAXIUNI] [char](1) NULL,
    [SOLAXICOM] [varchar](5120) NULL,
    [SOLAXIIDP] [char](1) NULL,
	[SOLAXICON] [char](8) NULL,
	[SOLAXICLA] [char](1) NULL,
	[SOLAXILIN] [char](8) NULL,
    [SOLAXIORI] [char](1) NULL,
    [SOLAXIGRU] [char](8) NULL,
	[SOLAXIAUS] [char](20) NOT NULL,
	[SOLAXIAFH] [datetime] NOT NULL,
	[SOLAXIAIP] [char](20) NOT NULL,
 CONSTRAINT [PK_SOLAXICOD] PRIMARY KEY CLUSTERED ([SOLAXICOD] ASC) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]) ON [PRIMARY]
GO

ALTER TABLE [CSF_PERMISOS].[adm].[SOLAXI] WITH CHECK ADD CONSTRAINT [FK_SOLAXICAB] FOREIGN KEY([SOLAXICAB]) REFERENCES [CSF_PERMISOS].[adm].[SOLFIC] ([SOLFICCOD])
GO
ALTER TABLE [CSF_PERMISOS].[adm].[SOLAXI] CHECK CONSTRAINT [FK_SOLAXICAB]
GO