CREATE TABLE [CSF_PERMISOS].[adm].[SOLFIC](
	[SOLFICCOD] [int] IDENTITY(1,1) NOT NULL,
	[SOLFICEST] [char](1) NOT NULL,
	[SOLFICTST] [int] NOT NULL,
	[SOLFICDOC] [varchar](100) NOT NULL,
	[SOLFICFE1] [date] NOT NULL,
	[SOLFICFE2] [date] NOT NULL,
	[SOLFICFEC] [int] NOT NULL,
    [SOLFICHO1] [char](5) NOT NULL,
	[SOLFICHO2] [char](5) NOT NULL,
	[SOLFICHOC] [decimal](3,1) NOT NULL,
	[SOLFICOB1] [varchar](5120) NULL,
    [SOLFICOB2] [varchar](5120) NULL,
    [SOLFICOB3] [varchar](5120) NULL,
    [SOLFICUSC] [char](20) NULL,
	[SOLFICFHC] [datetime] NULL,
	[SOLFICIPC] [char](20) NULL,
    [SOLFICUSA] [char](20) NULL,
	[SOLFICFHA] [datetime] NULL,
	[SOLFICIPA] [char](20) NULL,
    [SOLFICUST] [char](20) NULL,
	[SOLFICFHT] [datetime] NULL,
	[SOLFICIPT] [char](20) NULL,
	[SOLFICAUS] [char](20) NOT NULL,
	[SOLFICAFH] [datetime] NOT NULL,
	[SOLFICAIP] [char](20) NOT NULL,
 CONSTRAINT [PK_SOLFICCOD] PRIMARY KEY CLUSTERED ([SOLFICCOD] ASC) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]) ON [PRIMARY]
GO

ALTER TABLE [CSF_PERMISOS].[adm].[SOLFIC] WITH CHECK ADD CONSTRAINT [FK_SOLFICTST] FOREIGN KEY([SOLFICTST]) REFERENCES [CSF_PERMISOS].[adm].[DOMPAR] ([DOMPARCOD])
GO
ALTER TABLE [CSF_PERMISOS].[adm].[SOLFIC] CHECK CONSTRAINT [FK_SOLFICTST]
GO